CREATE DATABASE PROYECTOSEMINARIO1;
use PROYECTOSEMINARIO1;

CREATE TABLE PRODUCTO(
     id MEDIUMINT NOT NULL AUTO_INCREMENT,
     nombre CHAR(30) NOT NULL,
     precio INT NOT NULL,
     cantidad INT NOT NULL,
     PRIMARY KEY (id)
);
